### ISSUE TITLE
21737 build broken

### ISSUE THREAD

**Issue by LocutusCPlus** [WoW-Tools/CASCExplorer#10]
5/19 Beta build 21737 broke it. 

Please post updated CASCExlorer.zip package if you have working fix.

**Comment by team4music** [comment]
Can confirm that its totally broken

**Comment by Makpptfox** [comment]
Same here.

**Comment by LocutusCPlus** [comment]
Please to finding updated CASCExlorer.zip package.

Have you found fix to upload to make work?

**Comment by team4music** [comment]
Think there is sadly currently no one that could fix it.
