### ISSUE TITLE
Can't see/select CDN builds after latest update

### ISSUE THREAD

**Issue by Hyrja** [WoW-Tools/CASCExplorer#19]
Hey,

I can't see any CDN builds anymore after updating CASCExplorer today.
This is for every game.

Appreciate your work!

**Comment by Daenarys** [comment]
any plans to fix this soon(ish) ?

**Comment by Othernametwo** [comment]
People are waiting for fix too. Not only Daenarys.

**Comment by Daenarys** [comment]
still not working after new updates :/

**Comment by tomrus88** [comment]
Blizzard removed that information from CDN config files. It seems to be only present for SC2 and HOTS as of this comment.
