### ISSUE TITLE
Please close.

### ISSUE THREAD

**Issue by LocutusCPlus** [WoW-Tools/CASCExplorer#27]
No longer works, needs update.  Cannot open Patch 7.2 PTR data (local or online).  Can you release new compiled binaries.  Last release was July 2014.

Errors abut Content Flags.

![image](https://cloud.githubusercontent.com/assets/19483629/22311105/902503b4-e317-11e6-9456-64cb25b7d503.png)

**Comment by LocutusCPlus** [comment]
How to make work please?

**Comment by Farrarie** [comment]
I hope TOMRUSS teach us how to update the tool to everybuild

**Comment by LocutusCPlus** [comment]
Will you please re-compile and release fix??  Can't open to extract new models.

**Comment by LocutusCPlus** [comment]
Can someone release fix please?

**Comment by Farrarie** [comment]
it work with the current build

**Comment by noyel84** [comment]
Still not working for me

**Comment by LocutusCPlus** [comment]
No, it doesn't work with PTR build.

It only work with live build.

Need fix for it to work with PTR build.  Still broken.

Hopefully project not abandoned.

**Comment by Farrarie** [comment]
did you compile it
becuase I compile it and it work fine

**Comment by LocutusCPlus** [comment]
I don't know how to compile?  Can you post or send .zip file?

**Comment by Farrarie** [comment]
just open the sln
then change debug to release
and in build choose build solution
try youtube if you want video

**Comment by LocutusCPlus** [comment]
Resolved.

**Comment by noyel84** [comment]
Still no idea how to do, there is no SLN files in my casc folder

**Comment by noyel84** [comment]
![kekog](https://cloud.githubusercontent.com/assets/25705416/22924768/b04cc0ca-f2a6-11e6-8753-1d7a330983e3.png)
Well I tried some things, but now this is what I get when I open the 7.2
