### ISSUE TITLE
Open online storage does not work

### ISSUE THREAD

**Issue by TheWisp** [WoW-Tools/CASCExplorer#31]
Tried both Heroes of the storm retail and other games, none seems to work on my windows10 PC.
exception screenshot: http://imgur.com/a/kPJNN

**Comment by tomrus88** [comment]
Unable to reproduce and image link is dead.

**Comment by TheWisp** [comment]
How's imgur dead? reuploaded: https://pasteboard.co/1NLuXdhek.png

**Comment by MichaelPriebe** [comment]
I'm getting this error as well.
