### ISSUE TITLE
Can't open any online storage option.

### ISSUE THREAD

**Issue by xagonyx** [WoW-Tools/CASCExplorer#33]
Tried all WoW options (Retail, PTR and Beta) and other games, none is working
Screenshot here: http://imgur.com/a/E1py9
The error message is: One or more errors have occurred. Unable to connect to the remote server. An error occurred during the connection attempt because the connected part did not respond properly after a period of time, or an established connection failed because the connected host could not respond 37.244.26.18:80
WoW version: 7.2.5.24430

Edit: Already checked all .net installations and system files.

**Comment by MichaelPriebe** [comment]
I'm getting this error as well.
