### ISSUE TITLE
Cannot open WoW Storage

### ISSUE THREAD

**Issue by xagonyx** [WoW-Tools/CASCExplorer#34]
Tried opening WoW Storage located on C:\Program Files (x86)\World of Warcraft, the following error ocurred **Loading failed due to:**
Screenshot: http://imgur.com/a/sF1iz

WoW Version: 7.2.5.24430

**Comment by Marlamin** [comment]
Unsure if you fixed it yet, but this can be fixed through either having the Battle.net launcher repair your WoW installation or by renaming the indices folder inside WoW's Data folder to something else and launching WoW to let it recreate the files.

**Comment by kronflux** [comment]
Yep, just repaired my own install and now it's working perfectly, so I can confirm the solution.
Latest WoW verson

**Comment by Marlamin** [comment]
Awesome, thanks!
