### ISSUE TITLE
CASC will not load properly..

### ISSUE THREAD

**Issue by ShariAdune** [WoW-Tools/CASCExplorer#36]
i downloaded the Latest one, i have windows 10

the first image shows which thing i click on first from the zip file to start the program...
second image shows the error i get.

i got to my wow folder (not inside it) just the wow folder to request it get files from that folder.  please help :( this is getting frustrating.

i have also tried using other versions of CASC to no avail.
additionally, i tried going into the wow folder and changing the name of the indices folder, to something else, then started the game, then tried to open casc again... same error.

should the game be running or perhaps i need to cross my eyes a certain way to get this to work?

<a href="https://ibb.co/fnAhEk"><img src="https://preview.ibb.co/cTGNEk/1st.png" alt="1st" border="0"></a>
<a href="https://ibb.co/iKMB75"><img src="https://preview.ibb.co/d30hEk/error.png" alt="error" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>images uploader</a><br />

**Comment by ficarra1002** [comment]
Similar issue here, https://gyazo.com/d4e25d4fee2753cd6ca50b2e4eb575cd
