### ISSUE TITLE
Only WoW(Beta) is working

### ISSUE THREAD

**Issue by Hristiyanii** [WoW-Tools/CASCExplorer#39]
When i try ptr and retail sometimes it gives me errors some times stucked at downloading, why?

**Comment by Stanzilla** [comment]
Post the error

**Comment by Ammako** [comment]
Perhaps related, but I haven't been able to load retail on CASCExplorer for a while now.

![image](https://puu.sh/yZsSJ/7ca4f670d3.png)

PTR loads fine.

**Comment by Smerdokryl** [comment]
I think he is talking about the same error as https://github.com/WoW-Tools/CASCExplorer/issues/36

I get it too, but only if I select a storage to load, cancel the loading, and then try to select a different storage. If I restart the program and select any storage as the 'first try', all of them work fine
