### ISSUE TITLE
CASCconsole pauses during extraction till calling process terminates

### ISSUE THREAD

**Issue by Ahli** [WoW-Tools/CASCExplorer#43]
I am using CASCconsole to extract UI related game files from Heroes of the Storm and SC2 from a Java app.

It works fine when I call it from my .bat files, but now I am trying to execute it from my own Java app and I run into an odd problem:
In the beginning, it works fine up to a point where the extracted files should be written. Then, the three process instances my app started only sit there with 0 CPU usage and only continue after closing my Java app. It seems like everything is done besides writing the files to my HDD. Only a few files were written until it "pauses".

**TLDR:**
1. Java app starts 3 CASCconsole processes to export files matching three masks
2. CASCconsole processes run with a lot of CPU usage as expected
3. CASCconsole processes drop to 0% CPU usage after a while
4. Only a few files were extracted; not all of them.
5. Once the calling Java app terminates, the processes finish writing the last remaining files and terminate themselves.

Do you have any idea what could be causing this and how I could circumvent that issue?

In the end, I would like to wait for the CASCconsole process to finish from within my Java thread to be able to visualize that the extraction is running.

edit:
I am using the v0.21-alpha release.

**Comment by NunzioArdi** [comment]
try to compile the latest version.
Otherwise I have him compiled, you can download. https://drive.google.com/file/d/1t9uAvn4dK3BhYoHTL3g5jN9FzknJ40hC/view

Translate by Google translate

**Comment by Ahli** [comment]
The linked CASCConsole.exe does not extract any files. =/

Maybe you can spot, what I did wrong.

windows cmd.exe (added new required parameter local):
``` shell
F:\Spiele\GalaxyObsUI\tools\plugins\casc>CASCConsole.exe local *.StormLayout F:\Spiele\GalaxyObsUI\baseUI\heroes\ enUS None
Settings:
    WowPath: F:\Spiele\Heroes of the Storm Public Test
    OnlineMode: False
Loading...
CDNIndexHandler.Initialize() completed in 00:00:01.1659401
LocalIndexHandler.Initialize() completed in 00:00:00.2818437
new EncodingHandler() completed in 00:00:01.1426222
new RootHandler() completed in 00:00:01.6542942
new CASCHandler() completed in 00:00:04.2537777
MNDXRootHandler::SetFlags() completed in 00:00:00.8004313
Loaded.
Extract params:
    Mode: local
    Pattern: *.StormLayout
    Destination: F:\Spiele\GalaxyObsUI\baseUI\heroes\
    LocaleFlags: enUS
    ContentFlags: None
Extracted.
```

The CASCConsole.exe.config I created (the file was missing in the linked archive):
``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <configSections>
        <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
            <section name="CASCConsole.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false"/>
        </sectionGroup>
    </configSections>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.1"/>
    </startup>
    <userSettings>
        <CASCConsole.Properties.Settings>
            <setting name="StoragePath" serializeAs="String">
                <value>F:\Spiele\Heroes of the Storm Public Test</value>
            </setting>
            <setting name="OnlineMode" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="Product" serializeAs="String">
                <value>heroes</value>
            </setting>
            <setting name="Locale" serializeAs="String">
                <value>enUS</value>
            </setting>
        </CASCConsole.Properties.Settings>
    </userSettings>
</configuration>
```

**Comment by Ahli** [comment]
I figured out why the process stopped: Its streams had to be emptied. If its buffer was full, the process execution is halted. After redirecting the output, the current release is working for me.

The dev build's console.exe not extracting any files might be a lurking problem though (unless it is a user error if above files are incorrect).
