### ISSUE TITLE
Bosses VO's not Found

### ISSUE THREAD

**Issue by Fellandon** [WoW-Tools/CASCExplorer#48]
I've searched in every folder of the wow database but I can't find the new VO of Uldir bosses

**Comment by xoduddk123** [comment]
@Fellandon 
Did you find the voice of Uldir Boss?
I'm having the same problem.

**Comment by Fellandon** [comment]
you have to update the listlife file, to do that you have to open you listlife and swap the text for the text on this one https://github.com/wowdev/wow-listfile/blob/master/listfile.txt

**Comment by xoduddk123** [comment]
@Fellandon 
I got the voice from [Casc Storage](http://www.zezula.net/en/casc/main.html ) using `listfile.txt`.
It has helped a lot.
Thank you.
