### ISSUE TITLE
CASCHandler.FileExist(): Returns true on files that are already removed

### ISSUE THREAD

**Issue by megasus** [WoW-Tools/CASCExplorer#5]
rev 07a356ecb578ac8b10037e0f2b86277063b1a59c

For example:

Opening the latest WoW-Beta online storage and calling
`casc.FileExists("Interface\\Worldmap\\TheStoneCore\\TheStoneCore2.blp");`
Returns true, but the file doesn't really exist. You'll get an exception when calling OpenFile() on it.

Same is true for: "Interface\Worldmap\Hilsbrad\Hilsbrad1.blp" and other map files.

**Comment by tomrus88** [comment]
Pretty sure it worked like that since day one. Blame blizzard.
