### ISSUE TITLE
ListFile Error with newest Update/Trying to open / extract Classic

### ISSUE THREAD

**Issue by Dastano** [WoW-Tools/CASCExplorer#52]
---------------------------
Error
---------------------------
Loading failed due to:
System.FormatException: Die Eingabezeichenfolge hat das falsche Format.

   bei System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)

   bei System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)

   bei CASCLib.WowRootHandler.LoadListFile(String path, BackgroundWorkerEx worker) in C:\projects\cascexplorer\CascLib\RootHandlers\WowRootHandler.cs:Zeile 368.

   bei CASCExplorer.InitForm.backgroundWorker1_DoWork(Object sender, DoWorkEventArgs e) in C:\projects\cascexplorer\CASCExplorer\InitForm.cs:Zeile 56.

   bei System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)

   bei CASCLib.BackgroundWorkerEx.OnDoWork(DoWorkEventArgs e) in C:\projects\cascexplorer\CascLib\BackgroundWorkerEx.cs:Zeile 214.

   bei System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
---------------------------
OK   
---------------------------

**Comment by tomrus88** [comment]
In order to use latest version with classic you must provide listfile in new format.
If you don't have that listfile, use older version.
