### ISSUE TITLE
How to extract files with CASCConsole

### ISSUE THREAD

**Issue by omgvamp** [WoW-Tools/CASCExplorer#56]
I'd like to know how to extract files using the CASCConsole.

I tried the command below with the product set to hsb (Hearthstone) and online mode set to true in the config file, but without any result.

`.\CASCConsole.exe pattern *.txt . enUS True`

I get the following output:
```
Settings:
    WowPath: G:\Games\World of Warcraft\
    OnlineMode: True
Loading...
CDNIndexHandler.Initialize() completed in 00:00:00.0298308
new EncodingHandler() completed in 00:00:00.0132399
new RootHandler() completed in 00:00:00.5836199
new CASCHandler() completed in 00:00:00.6342056
HSRootHandler::SetFlags() completed in 00:00:00.0005148
Loaded.
Extract params:
    Mode: pattern
    Pattern/Listfile: *.txt
    Destination: .
    LocaleFlags: enUS
    OverrideArchive: True
Extracted.
```

But nothing is actually extracted. Any help would be greatly appreciated!

**Comment by tomrus88** [comment]
I've tried this
`CASCConsole.exe pattern *.cur test enUS hsb false`
and it worked fine for me.
