### ISSUE TITLE
Error loading wow_beta locally

### ISSUE THREAD

**Issue by yoshimo** [WoW-Tools/CASCExplorer#63]
When i select wow beta (which was uninstalled already) i get

`---------------------------
Error
---------------------------
Loading failed due to:
System.Exception: Can't find active BuildInfoEntry

   bei CASCLib.CASCConfig.LoadLocalStorageConfig(String basePath, String product, ILoggerOptions loggerOptions) in C:\projects\cascexplorer\CascLib\CascLib\CASCConfig.cs:Zeile 263.

   bei CASCExplorer.InitForm.backgroundWorker1_DoWork(Object sender, DoWorkEventArgs e) in C:\projects\cascexplorer\CASCExplorer\InitForm.cs:Zeile 32.

   bei System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)

   bei CASCLib.BackgroundWorkerEx.OnDoWork(DoWorkEventArgs e) in C:\projects\cascexplorer\CascLib\CascLib\BackgroundWorkerEx.cs:Zeile 214.

   bei System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
---------------------------
OK   
---------------------------
`
Same happens for the classic_beta

**Comment by tomrus88** [comment]
Works for me.
