### ISSUE TITLE
Problem of loading osi retail

### ISSUE THREAD

**Issue by CaiMiao** [WoW-Tools/CASCExplorer#65]
Game: Diablo 2 resurrected `osi` retail
Both offline and online only shows `jaJP` language files
No locale flags

![image](https://user-images.githubusercontent.com/4640483/135928327-3e622864-081e-4432-8975-660b95317441.png)

**Comment by tomrus88** [comment]
This is not true.

There's was a bug where jaJP were flagged as available to all locales, but english files were still available in theirs folders.
Also locale selector wasn't active for this game.
All of that should be fixed now.
