### ISSUE TITLE
Error Open HOTS

### ISSUE THREAD

**Issue by ascent-sys** [WoW-Tools/CASCExplorer#66]
Does not open HOTS, not online, not offline.
![1](https://user-images.githubusercontent.com/61962629/149467682-cec3aa12-4dd5-48c5-beb7-06d3c8cf7be9.png)
CASCExplorer-v1.0.162

**Comment by ascent-sys** [comment]
CASCExplorer-v1.0.163 - not fixed.

**Comment by tomrus88** [comment]
Works fine for me.

**Comment by ascent-sys** [comment]
> Works fine for me.

Now yes, it works)
