### ISSUE TITLE
COD: Modern Warfare online storage download error

### ISSUE THREAD

**Issue by m0xf** [WoW-Tools/CASCExplorer#69]
Files not downloaded properly.  
To download file used partial eKey (9 bytes), instead of full eKey.  Full eKey (16 bytes) located in "download" file.

example:
- CASCExplorer http query:
`GET /tpr/odin/data/ad/50/ad50ee5d0a540e00d100000000000000 HTTP/1.1`
- correct query:
'GET /tpr/odin/data/ad/50/ad50ee5d0a540e00d148d1dce6a73562 HTTP/1.1'

**Comment by tomrus88** [comment]
Fixed, may be.
