### ISSUE TITLE
[wow] 6.2.3 и ниже

### ISSUE THREAD

**Issue by soulfrost** [WoW-Tools/CASCExplorer#7]
отлично работает с легионом, а вот с 6.2.3  - 6.2.4 и ниже что-то случилось, не хочет показывать файлы ( все как будто не известного формата ) - выходит как-то так на версии 6.2.3
![image](https://cloud.githubusercontent.com/assets/2207154/14590763/af2962fe-050b-11e6-825a-eb4ebd109f9c.png)

**Comment by tomrus88** [comment]
До легиона нужен listfile.txt со списком файлов.
