### ISSUE TITLE
1GB+ files are not properly downloaded/extracted

### ISSUE THREAD

**Issue by modusc896d352** [WoW-Tools/CASCExplorer#71]
so i opened up **CALL OF DUTY VANGUARD** online storage, tried to extract an 1GB+ file (sp_rus_summer.bik) from there and CASCExplorer could only write an 0KB file instead,
on another note, **CALL OF DUTY BLACK OPS IIII** has many 1GB+ files that pass the mark (up to 21GB) and from the looks of it CASCExtract may not even be able to extract a handful of them.

is there any way this can be fixed at all?

**Comment by tomrus88** [comment]
Should work now.
