### ISSUE TITLE
Error while extracting db2 from WoW retail

### ISSUE THREAD

**Issue by fechan** [WoW-Tools/CASCExplorer#77]
On the latest commit: I'm trying to extract DB2 files from WoW retail using the following command: `CASCConsole.exe -m listfile -e testlistfile.csv -d output -l enUS -p wow -o true`. The test listfile contains just a single line:

If the listfile contains `3286804;dbfilesclient/animacylinder.db2` then I get `Extracting '3286804;dbfilesclient/animacylinder.db2'... Error (6599245EB3832549)!`

If the listfile contains `dbfilesclient/animacylinder.db2` then I get `Extracting 'dbfilesclient/animacylinder.db2'... Error (A043036B06F4A20F)!`

In either case, nothing gets extracted. This happens even if I use a local installation of WoW instead of the online source. Also I've tried a bunch of other db2 files and none of them work either.

I've also tried `-m pattern -e *.db2`, and nothing gets extracted.

Other types of files seem to work, since if I use `-e *.*` various files get extracted, but no `.db2` files.

**Comment by tomrus88** [comment]
Can't reproduce.
